### ISSUE TITLE
Torrent Control trying to load torrent from 127.0.0.1 - Network error

### ISSUE THREAD

**Issue by robertheadley** [Mika-/torrent-control#100]
![image](https://user-images.githubusercontent.com/1780455/95934037-7fc77b80-0d95-11eb-934c-19f166205898.png)

This does not happen with every torrent, but 98% of them.
I get a popup that says 

![image](https://user-images.githubusercontent.com/1780455/95934500-98846100-0d96-11eb-8d5b-6829f2ff4270.png)

I have attached the network log from my extension debug for Firefox. 

[c6b87ed5-b678-4268-be7b-17f392c5bdeb_Archive [20-10-13 20-46-56].zip](https://github.com/Mika-/torrent-control/files/5375102/c6b87ed5-b678-4268-be7b-17f392c5bdeb_Archive.20-10-13.20-46-56.zip)

**Comment by Mika-** [comment]
This happens when rTorrent is running in a container or other type of jail preventing it from seeing the real server address. As rTorrent can't see the real address this results as invalid redirect to localhost or container hostname as seen "right" from inside the jail.

Best way could be to add url rewriting to force these redirects to always point to a hostname configured in addon settings.

**Comment by robertheadley** [comment]
It worked previously. I verified that I can connect to my server fine on other browsers.

**Comment by Mika-** [comment]
Rutorrent change was done in april ([345dbe5](https://github.com/Novik/ruTorrent/commit/345dbe58a892f1d05b7e6235d630b0bb6741229e)). Previously redirect was just a relative path without hostname.

**Comment by robertheadley** [comment]
I notified an admin for rapidseedbox. Thank you.

**Comment by robertheadley** [comment]
My admin made the change but I am still experiencing the same problem. I actually get a 404 if I choose Flood though.

**Comment by robertheadley** [comment]
Is this something that will have a workaround in a future version of your extension?

**Comment by Mika-** [comment]
I tested to handle redirects manually, but it may not be possible or atleast it's going to need some hacky solution.
By the current fetch [specification ](https://fetch.spec.whatwg.org/#atomic-http-redirect-handling) there's no way to get the redirected url.

**Comment by robertheadley** [comment]
Maybe a checkbox to hardcode the addtorrent.php script location?
Mine is located at https://*myip*/rutorrent/php/addtorrent.php but the script is trying to access //127.0.0.1:8080/php/addtorrent.php?result[]=FailedDirectory&json=1

missing the /rutorrent

**Comment by Mika-** [comment]
In that case your server address should be configured as `https://myip/rutorrent/`.
I think there may be cases that prevent rutorrent from seeing the proper path due path rewriting on reverse proxy.

**Comment by robertheadley** [comment]
Yeah, that is how I have it configured. I know that this is probably my admin's problem and not yours, but they have kind of closed the issue out as resolved.
