### ISSUE TITLE
torrent-control tries to login even when credentials are unset

### ISSUE THREAD

**Issue by ThinkChaos** [Mika-/torrent-control#103]
I already use torrent-control with an internet facing machine and it works great.
I now also want to use torrent-control to add torrents to a machine on my home LAN. I use flood with `--auth=none` as this is my LAN and I trust it.

Leaving the username and password fields doesn't change the way the extension tries to add torrents: it still goes through the login.
Flood responds with a 404 since its `/auth` endpoint is disabled, and torrent-control bails. Looking at the code this isn't specific to Flood.

I would expect the extension not to attempt login when username and password are empty. Can you please change that?

EDIT: I digged a bit more, and noticed that the updated URLs from #102 weren't released yet. So that's also a blocker right now for me.

**Comment by Mika-** [comment]
I added this feature, but I cannot test it, as flood seems to be currently broken if you use auth=none and a qbittorrent backend.

**Comment by ThinkChaos** [comment]
I created an issue over there: jesec/flood#103 (numbers are in sync with this repo :slot_machine:) and the conclusion was that even with `auth=none` the API should still be authenticated (any creds work) just to obtain a token - as it is stated in docs I had missed.
I think it's a pretty useless security measure but apparently Transmission also works like that so he wants to keep it.

Anyways I don't personally need the fix anymore, but still think it's more sensible not to authenticate when there are no credentials. If you push on a separate branch I can setup a FF profile to test the extension.

**Comment by jesec** [comment]
I just gave an example (Transmission). Transmission's technical design is not related to Flood.

It is an important security measure. Without such protections, an attacker may initiate arbitrary downloads or change settings of your Flood server in harmful ways. They don't even need your credentials (or even interaction) as they use your browser to send requests.

**Comment by jesec** [comment]
No action is required here. Flood unconditionally sent token when /verify or /authenticate endpoints are accessed while auth=none. So it is perfectly OK to send empty username and password.

**Comment by Mika-** [comment]
Checked the same thing from the source. Flood just doesn't seem to care about credentials if noauth mode is used.

Just pushed a new version with support for the new flood api, that should fix things for you.

**Comment by ThinkChaos** [comment]
> It is an important security measure. Without such protections, an attacker may initiate arbitrary downloads or change settings of your Flood server in harmful ways. They don't even need your credentials (or even interaction) as they use your browser to send requests.

I understand all of that but don't see how if an attacker can send a request to add a torrent or do other harmful things, they can't also send a request to `/api/auth/authenticate` so the browser gets a valid cookie.
I'm not that well versed with web security though so I could very well be wrong.

> Just pushed a new version with support for the new flood api, that should fix things for you.

I just tested and it works as expected, thanks!
