### ISSUE TITLE
Flood (4.1.X): Can't use "default" as download location

### ISSUE THREAD

**Issue by ihatemyisp** [Mika-/torrent-control#105]
I believe this is caused by changes to the Flood API's handling of destination property introduced in 4.1.0.

From what I gather, if we're wanting to use the "default" location of the client (rTorrent in my case), the destination property should be omitted altogether from the API request instead of sending a empty destination property.

If we send the property, even if it's empty, Flood will think it's valid and try to pass it to the client.

**Comment by Mika-** [comment]
Floods own ui looks like to be using empty string in it's requests. And according to [this](https://github.com/jesec/flood/blob/master/server/routes/api/torrents.ts#L33) empty destination string is converted to undefined. So both should behave the same way.

**Comment by ihatemyisp** [comment]
Hmm, perhaps it's something on my configuration, I just recently switch to 4.1.

What I do know is that the exact same torrent will work if I select a destination vice "default". If I leave default selected I get an 500 error with a JSON response of "code: EACCES".

I'll investigate further.

**Comment by ihatemyisp** [comment]
JavaScript is not my wheelhouse, so I'm hard core lost in this. I bypassed my nginx proxy to see if that changes anything, but it doesn't and unfortunately Flood doesn't have a lot of logging or error handling.

I'm not sure what's causing this. For now though I'll just select a destination every time.

**Comment by jesec** [comment]
EACCES means permission denied. You probably configured the `--allowedpath` and the default destination of your torrent client is not an allowed path.

**Comment by ihatemyisp** [comment]
I checked that as well and for testing removed `--allowedpath`, with no change.

**Comment by ihatemyisp** [comment]
@jesec I saw you added a snippet to force a temp folder for the download.

Will that change fix this issue?

**Comment by jesec** [comment]
The change will mitigate the problem by making sure that there is a last resort. However, I would advise you to debug Flood if possible. Place some breakpoints in getDestination function and see which step does not give the expected result. Check `development` section of README for more details. You can easily debug with VS Code, even when Flood is installed on a remote machine.

**Comment by ihatemyisp** [comment]
@jesec and @Mika-, I've tracked it down. It's a bug in Flood, I think.

[This line](https://github.com/jesec/flood/blob/3e538f78fac5e8fc7f510e8e1f7465fd5b8c23e1/server/routes/api/torrents.ts#L47) and the next line set autoDestination to an array, which causes sanitizePath to throw accessDeniedError as it's expecting a string.

As I'm not versed in JS, I believe I have a fix, but my testing/debugging setup does not allow me to fully test this fix.

Change [this line](https://github.com/jesec/flood/blob/3e538f78fac5e8fc7f510e8e1f7465fd5b8c23e1/server/routes/api/torrents.ts#L48) to the following:

`    autoDestination = directoryDefault[0];`

VS Code balks at it, but from what I can tell, it works.

**Comment by jesec** [comment]
@ihatemyisp 

Interesting.

`directoryDefault` is supposed to be a `string`:
https://github.com/jesec/flood/blob/3e538f78fac5e8fc7f510e8e1f7465fd5b8c23e1/shared/types/ClientSettings.ts#L4

I will take a look at the issue.

**Comment by ihatemyisp** [comment]
Awesome, let me know if I can be of any assistance.

**Comment by jesec** [comment]
https://github.com/jesec/flood/commit/b00572a6fc7f03da7c5b45f809d8c27ba099ba20

**Comment by ihatemyisp** [comment]
Fantastic. Because I’m lazy, I’ll wait for the next release to drop and get hit npmjs.

Thanks for looking into this.

**Comment by ihatemyisp** [comment]
> jesec/flood@b00572a

Fixed by this commit.
