### ISSUE TITLE
ruTorrent v.3.10 - Torrent added as paused

### ISSUE THREAD

**Issue by Loginbug** [Mika-/torrent-control#107]
Hello,
i'm using latest ruTorrent version, i'm not using "_Add torrent as paused_" option, but when i add a torrent with torrent-control the torrent is added as stopped state and it does not start as i aspect.

**Comment by Mika-** [comment]
ruTorrent api only allows to pause torrents. So behaviour defaults to rTorrent default if the setting is not enabled in torrent control.

**Comment by Loginbug** [comment]
Thanks
