### ISSUE TITLE
Removed from Firefox?

### ISSUE THREAD

**Issue by reedrw** [Mika-/torrent-control#110]
I just noticed that the [Firefox extension page](https://addons.mozilla.org/en-US/firefox/addon/torrent-control/) for this is gone. What happened?

**Comment by Mika-** [comment]
Mozilla introduced a mandatory privacy policies for addons. They did a bulk disable for addons that didn't have policy defined, but it also impacted some addons that were fine (like this one).

AMO moderator asked me to push a rerelease yesterday, and it's currently in a review queue at position 39/64. With the current pace it could take couple of days to show up.

**Comment by Mika-** [comment]
Mozilla has reviewed the addon and it's available again.
