### ISSUE TITLE
add rutracker.org and kinozal.tv private tracker torrent download url to witelist

### ISSUE THREAD

**Issue by sun1ight** [Mika-/torrent-control#111]
In util.js

download torrent url example: https://rutracker.org/forum/dl.php?t=6012033
Tested tegexp:
`const whitelist = [
/\/dl\.php\?t=\d+/, //rutracker
];`

download torrent url example: http://dl.kinozal.tv/download.php?id=1560368
Untested tegexp, but should work:
`const whitelist = [
/\/download\.php\?id=\d+/, // kinozal
];`

**Comment by Mika-** [comment]
Newest version now has support for user defined regular expressions.
