### ISSUE TITLE
Help create a rule for the site

### ISSUE THREAD

**Issue by Alexey71** [Mika-/torrent-control#112]
Torrent https://rezka.cc/r/7672-molodoy-skala-2021-1-sezon-9-seriya-hdrezka-studio/fhd/1619054499
It does not help
`/https:\/\/rezka.cc\/r\/+?\/fhd\/+?/`
Help correct how it will be the right way?

**Comment by Mika-** [comment]
You are missing a character to match. The basic match is `.+?`. `.` for any character,  `+` atleast one time and `?` for non-greedy.
`/https:\/\/rezka.cc\/r\/.+?\/fhd\/.+?/`

**Comment by Alexey71** [comment]
Thank you so much. Fast support and excellent addition.
