### ISSUE TITLE
401 Unauthorized on flood + nginx reverse proxy + basic auth

### ISSUE THREAD

**Issue by jagaimoworks** [Mika-/torrent-control#115]
Trying to add torrents yields a 401 Unauthorized error. I run flood version 4.6.1 behind a nginx reverse proxy configured for basic auth. flood is run with the `--auth none` option.

Clicking the torrent-control toolbar icon behaves as expected. On the first visit it asks for credentials which if provided correctly lands you on floods landing page. Subsequent tries make use of the cached credentials but adding torrents still won't work.
I was under the impression that this had worked in the past.

**Comment by dspearson** [comment]
I also have the same use-case. I trust nginx basic auth to be more battle-tested than exposing flood to the wider internet.

**Comment by Mika-** [comment]
This is actually already partially implemented for Deluge in #44, as it only uses password for authentication. Almost no one knows it even exists so it's about time to upgrade it to a proper feature.

I'll add config option for Flood, Deluge and qBittorrent:
![httpauth](https://user-images.githubusercontent.com/5081253/128601153-5340c4dc-b72e-4129-8d81-aac5e1fad90c.png)
