### ISSUE TITLE
Not adding torrent to qbittorrent web UI

### ISSUE THREAD

**Issue by yazeed44** [Mika-/torrent-control#116]
I'm not getting any dialog indicating any error or progress. I have checked the web UI and the torrent have not been added either.

I tried adding the torrent in the context menu but it's not getting added. The same thing for magnet links

When I click on the extension icon in the toolbar it sends me to the web UI correctly though.

qBittorrent v4.3.7
Firefox 91.0.1

**Comment by Mika-** [comment]
What error are you getting (if any)? I'm running same versions without issues.

Note that qBittorrent doesn't give meaningful error when torrent already exists.

**Comment by yazeed44** [comment]
I'm not getting any error in qBittorrent Web UI or Firefox.

Note that I'm accessing qBittorrent Web UI over http not https
