### ISSUE TITLE
Not working if ruTorrent authentication requested is not "Basic"

### ISSUE THREAD

**Issue by Delgan** [Mika-/torrent-control#12]
Hi again.

I have trouble configuring `torrent-control` so that it can work on ruTorrent, I always have "Failed to login" error.

After digging through the code, I think this is maybe because of `torrent-control` using "Basic" authentification while my seedbox only accept "Digest". I am not sure because I do not know much about HTTP requests en Authentification, but after looking manually at the headers on my browser, Firefox automatically use Digest and the server does not return 401.
I the auth is not Digest, the response header looks like this (status code = `401 Unauthorized`):
```
Date: Thu, 11 Jan 2018 20:03:35 GMT
Server: Apache/2.4.18 (Ubuntu)
WWW-Authenticate: Digest realm="rutorrent", nonce="9EuWjkXcYDE=adf164bbt687a3e33727f321104f1e0de1hp365d", algorithm=MD5, qop="auth"
Content-Length: 462
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: text/html; charset=iso-8859-1
```

According to the documentation, the request header [`Authorization`](https://developer.mozilla.org/docs/Web/HTTP/Headers/Authorization) has to be set after a 401 response, the 401 response contains a [`WWW-Authenticate`](https://developer.mozilla.org/docs/Web/HTTP/Headers/WWW-Authenticate) header which should be used to determine the proper authentification method.

But there exist many methods, we need something generic rather than implement them all.

The [`fetch()`](https://developer.mozilla.org/docs/Web/API/WindowOrWorkerGlobalScope/fetch) function is described as accepting an `init` parameter, which itself may contain a `credentials` value. The latter could accept a [`PasswordCredential`](https://developer.mozilla.org/docs/Web/API/PasswordCredential) object which looks nice, but unfortunately is only available in Chrome, not Firefox...

Before Firefox Quantum I used `bittorrent-webui` which worked very well with my seedbox. So I looked at [the source code](https://github.com/GodKratos/bittorrent-webui/blob/7a9df9b8f8dcbb396779a9367c74c00caff91d75/chrome/content/ruTorrentDispatcher.js#L63-L64), and it seems it was using [`XMLHttpRequest.open()`](https://developer.mozilla.org/docs/Web/API/XMLHttpRequest/open) which I guess take care of formatting authentification as requested.

Do you have any idea how we could integrate this with `torrent-control` using `fetch()` or something else? Because I must admit that I have not managed to make it work unfortunately.

**Comment by Mika-** [comment]
I have been thinking about moving http authentication to `[onAuthRequired](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest/onAuthRequired)` listener to provide auto login for web interfaces. By reading trough docs it looks like this would also give support for http digest authentication as a side feature.

**Comment by Delgan** [comment]
I tried using `onAuthRequired` but I could not make it work, except when I was asked for credentials by the browser after browsing manually to the webpage. Maybe you will be luckier than me, I do not know all these APIs very well.

In the meantime I use the extension `torrent-to-web`, they seem to implement [another solution](https://github.com/DASPRiD/Torrent-to-Web/blob/cfdd825dc57b21cc852c0839275f1cff5792d0ef/background/adapter/rutorrent.js#L10-L12) using the [`URL()`](https://developer.mozilla.org/en-US/docs/Web/API/URL) API.

**Comment by Mika-** [comment]
I had finally some time to test this and onAuthRequired provides credentials properly. I'm a bit busy at a moment but I'll try to get this done by next weekend.

**Comment by Delgan** [comment]
Thank you for your help on this bug. 👍 

Take your time, especially if you are busy with other things, I am in no hurry.

**Comment by Mika-** [comment]
Just did some last tests and pushed a new version with onAuthRequired handling enabled for ruTorrent. Can you check if that works for you?

**Comment by Delgan** [comment]
This is working wonderfully well! 🎉 

Thank you for the quick fix!
