### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by neo-neo1** [Mika-/torrent-control#122]
Very useful addon but we need dark mode. For those of us who use OS and Browser wide dark mode having a white window looks out of place and an eye sore for us pedantics. Can you please let us choose specific background color with a color code field? Or at least add an option for dark mode (dark gray background color preferred).

<img width="823" alt="ScreenShot 2021-11-29 at 6 19 34 AM" src="https://user-images.githubusercontent.com/6996362/143859428-17089bbb-220d-4b29-ab78-917a48fcfecf.png">

**Comment by Mika-** [comment]
Firefox doesn't have native dark theme for addons, so supporting this requires fully custom styling.
Included styling is overall pretty terrible to work with, and I have already been thinking replacing it many times.

**Comment by neo-neo1** [comment]
> 
> supporting this requires fully custom styling. 

At the very minimum, a HTML color code field to enter for background color would be a tremendous improvement.
