### ISSUE TITLE
Add torrent (advanced) windows needs resize every time

### ISSUE THREAD

**Issue by shama84** [Mika-/torrent-control#126]
when using "Add torrent (advanced)" contextual entry a windows appears with the options to select. since I get a monitor with 1440p resolution this windows need to be resized to show all options. The size chosen is not retained hence it needs to be done every time.

Do you think possible to retain the size or to display a bigger a windows (no resize needed)?

**Comment by shama84** [comment]
FMI: Any update ?

**Comment by Mika-** [comment]
There's no easy way to fix this properly, as everything from installed addons to system font affects to total window height. Hopefully some extra height helps.
