### ISSUE TITLE
Deluge 2.1.0 - Failed to Login

### ISSUE THREAD

**Issue by Groodles** [Mika-/torrent-control#129]
![image](https://user-images.githubusercontent.com/24456579/177053881-cbf34910-6691-4d59-835f-07b18f5108ed.png)

Just updated from Deluge 2.0.3 to 2.1.0 and Torrent Control can no longer send via the Deluge WebUI.

**Comment by Mika-** [comment]
Tested this and can't reproduce. 2.1.0 web api seems to be same as before
