### ISSUE TITLE
[Feature Request] Multiple client support

### ISSUE THREAD

**Issue by typhoon71** [Mika-/torrent-control#13]
Just a suggestion, since firefox webext is not really mature/complete yet, so it may be not feasible right now.

Right now if you click the extension icon you're taken to the webclient.
I would prefer it it would toggle the extension on/off instead, maybe with a right click opt menu.

That way I could send magnet to my local client when it's off, OR to the remote client if it's on.
I think this would need to wait for proper mimetype handling to be implemented i ffox58?

Would this be feasible? Thanks anyway, this addon is already helpful in replacing the pre ffox57 ones.

**Comment by Mika-** [comment]
Magnet links are handled trough protocol handler which can't be turned off without uninstalling or disabling the whole extension.

Support for multiple clients is actually planned and partially implemented, but still needs some work. With multiple clients configured, magnet links would be send to "active" or "default" client, which could be changed quickly via extension icons context menu.

**Comment by jaypan** [comment]
Love the plugin, thanks! I look forward to the multiple client support when you are able to do it.

**Comment by Mika-** [comment]
Multi server support is now added. Active server can be switched via browser actions context menu.

**Comment by jaypan** [comment]
Thank you for your work, much appreciated.

How do we add additional servers? I've upgraded to 0.1.12, but I don't see any options to add an additional server in there.

**Comment by jaypan** [comment]
Ok, I figured out I need to be on 0.2.0.

I've added in another server, but I can't seem to figure out how to use it. There is no option to switch servers in the context menu, and in the add-on settings, I can select my new server in the 'current server' options, but when I leave the page and come back, it is still set to the original.

**Comment by jaypan** [comment]
And I figured that out too :)

For anyone else, to switch servers, you need to right-click the icon in the toolbar, and select the server you want. Then when right-clicking a torrent link, it will send to the server you selected.

Thanks a lot for the work on this, it's a great new feature!
