### ISSUE TITLE
Constant refresh after clicking on the "Torrent Control" extension with Transmission

### ISSUE THREAD

**Issue by kozak-codes** [Mika-/torrent-control#131]
I have Torrent Control 0.2.27 installed on Firefox 102.0 (64-bit). When I click "Torrent control" it opens transmission and logs me in, but it reloads the page every second or so meaning I can't do anything on the transmission UI.

Reloading the page manually seems to solve the problem.

Is there any way we can disable the automatic reload functionality for Transmission?

**Comment by KleptoKat** [comment]
This issue seems to be related to:
```javascript
                else if (response.status === 409 && response.headers.has('X-Transmission-Session-Id'))
                    return this.logIn().then(() => resolve());
```

in [transmission.js](https://github.com/Mika-/torrent-control/blob/master/src/lib/transmission.js) 

Somehow this causes an infinite loop/recursion when we call `this.login` again. However, the system already successfully authenticated.

**Comment by Mika-** [comment]
Never managed to reproduce this, but the latest version has some fixes to Transmission session handling that could fix this
