### ISSUE TITLE
how to connect to client from outside my network?

### ISSUE THREAD

**Issue by GeneralUser-NonDev** [Mika-/torrent-control#132]
Hi all, Not that I use this much but I have a "setup" question. How can I make this access my download client from outside my network (or through a VPN Tunneled browser)? say I'm at a friends house or something and I find something I want my downloader to download how can I tell it to? I tried changing the "127.0.0.1:xxxxx" in the settings to the link my DuckDNS my Wireguard is using but that didn't work, Do I have to make another setting in my DuckDNS for it with a specific port (if even possible, Haven't looked) or would a reverse proxy (not sure what that is but seen it mentioned on Unraid YouTube Videos) to make this work?

**Comment by Mika-** [comment]
This addon only needs to have access to clients web interface. Same as you would use it via browser.

You can expose it by having dynamic dns (like DuckDNS) to point to your servers ip, and exposing it via open port or fancier reverse proxy setup. Or you can left it unexposed and connect to your network with vpn and access it with internal ip address.
