### ISSUE TITLE
Cannot use Auth Basic with an IPV6 Server address. 

### ISSUE THREAD

**Issue by Antorell** [Mika-/torrent-control#133]
Hi,

My server has an IPV6 address to connect to Rutorrent, and login in using Auth Basic doesn't seem to work if I set an IPV6 IP [2xxx:xxx:xxx:xxx:] in the Server address. The extension returns a "login failed" error as if it was the server that refused the login/password, however the server was never reached at all. Nginx doesn't show any login errors like it does when I try with an IPV4 and an incorrect login or password. 

If I swap the server's IPV6 IP for the server's IPV4, the extension logs in the server without issue. 

Edit:  There's a 401 log but it's in Nginx's access.log instead of the error.log for some reason. I tried the url in my browser and Rutorrent added the torrent normally. 

`/php/addtorrent.php?json=1&url=magnet( REMOVED )&torrents_start_stopped=true HTTP/2.0" 401 172 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0"`

**Comment by Mika-** [comment]
Nicely spotted. Forgetting that ipv6 addresses exist has been pretty big oversight.
