### ISSUE TITLE
Failed to read torrent (Unkown type)

### ISSUE THREAD

**Issue by Antorell** [Mika-/torrent-control#139]
It started out of the blue, the extension was working fine a couple of days ago. I downgraded to 0.2.29, and it's working fine again. All the versions from 0.2.30 to 0.2.32 have this issue. 

torrentgalaxy.to
any torrent
using this regex to catch torrent files:
/^https:\/\/watercache\.nanobytes\.org\/get\//i

The request header for the torrent file when torrent-control is not enabled:
```
HTTP/2 200 OK
server: nginx
date: Wed, 09 Nov 2022 03:51:19 GMT
content-type: application/x-bittorrent, application/octet-stream
content-disposition: attachment; filename="1234567890-TORRENTGALAXY.torrent"
strict-transport-security: max-age=63072000; preload
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
X-Firefox-Spdy: h2
```

**Comment by Mika-** [comment]
Firefox seems to return empty mime type for blob when encountering multiple types. Added empty as allowed type in the latest version.
