### ISSUE TITLE
Unable to download torrent on some trackers

### ISSUE THREAD

**Issue by Delgan** [Mika-/torrent-control#14]
Hi.

I tried to fix it by myself but I could not find what was going wrong.

Basically, while trying to download a torrent on this tracker: https://yggtorrent.com/ (most popular semi-private french tracker), I get a "Failed to add torrent" error.
Actually, my PR #11 was wrong and should be reverted. The returned response type is indeed "text / html", but it does not contain torrent bytes, it contains a string: "Vous devez vous connecter pour télécharger un torrent" which imply that for some reason the credentials are not properly supplied to the get request.

I tried to pass cookies and headers manually from my browser to the `fetch()` function but it did not work any better.

**Comment by Mika-** [comment]
I tried to duplicate this, but that site looks like to be working fine. Authentication is just a normal cookie and it gets sent properly along all the cloudflare and ga cookies.

**Comment by Delgan** [comment]
So you was able to successfully start torrent download from this website? That is weird, I tried with ruTorrent en Utorrent clients but both returned the same error.

It may be related to something with my Firefox configuration or modules then, I will try to investigate this again when I have some time.

Thank you for having checked that.

**Comment by Mika-** [comment]
Yes. Extension makes torrent fetching request look like normal browser navigation requests including cookies. The only thing different is the `Accept` header which triest to hint servers to serve torrent files (`application/x-bittorrent,*/*;q=0.9`). There's propably no torrent sites that even check this header, but atleast we are following the http spec...

**Comment by Delgan** [comment]
Finally figured out what was causing the bug!

This is because of Firefox blocking third-party cookies by default.

![2017-10-21-05-17-52-3f3f1c](https://user-images.githubusercontent.com/4193924/35768319-41f5ee1a-08fa-11e8-9486-c3790ae0553c.png)

I added an exception accept it from Yggtorrent and it works fine now. 👍
