### ISSUE TITLE
Directories doesnt get applied in qbittorrent and rutorrent

### ISSUE THREAD

**Issue by DoucheHellSung** [Mika-/torrent-control#141]
title + this feature only seems to work in deluge

**Comment by Mika-** [comment]
I'm using that feature daily with qbittorrent so it does work. Double check your download paths, as clients often just silently fail or use defaults when those are wrong.

**Comment by DoucheHellSung** [comment]
> I'm using that feature daily with qbittorrent so it does work. Double check your download paths, as clients often just silently fail or use defaults when those are wrong.

I have defined the paths same way for deluge, can you give an example

**Comment by Mika-** [comment]
Another thing is to always use absolute paths. Like `/mnt/disk-1/qbittorrent/data` and not just `data`. Without error messages and other debug info I can't help more.
