### ISSUE TITLE
[Feature request] Position of context menu option

### ISSUE THREAD

**Issue by simonbcn** [Mika-/torrent-control#143]
Would it be possible to position the submenu of this extension in the first position (_or at least further up_) in the context menu (_right mouse click_)?

**Comment by simonbcn** [comment]
Another possibility (_if technically possible_) could be the option to color (_or **bold**_) that option to make it more visible.

**Comment by Mika-** [comment]
If you are referring to context menu that opens for links, I'm afraid that web extension apis don't allow any customization. It seems like addons are presented in installation order.
