### ISSUE TITLE
Cannot handle long magnet links

### ISSUE THREAD

**Issue by Qazy147** [Mika-/torrent-control#149]
If magnet link is longer than 1024 characters, it shows error "JSON.parser: unexpected character at line 2 column 1 of the JSON data".

**Comment by Mika-** [comment]
Which torrent client are you using? There's no handling on extensions side and the error indicates that it's a problem in torrent client (or possible reverse proxy before it).

**Comment by Qazy147** [comment]
It is µTorrent. So if it is not extension problem, is it possible to add option to truncate magnet link? Just cut off last few "&" parts?

**Comment by Mika-** [comment]
It depends what is in those parts. Most likely those are tracker urls and some can be dropped. Even thought it could prevent connecting some peers, making torrent slower or completely unavailable depending it's health.

**Comment by Qazy147** [comment]
In my opinion, slow is still better than none.

**Comment by Anorak-Stan** [comment]
I get the same problem
When trying to click link on this torrent
https://tpb.party/torrent/70636448/TuneIn_Radio_Pro_-_Live_Radio_v32.0.2_Paid_Apk
I get the same "JSON.parser: unexpected character at line 2 column 1 of the JSON data" error
Have tried various Bit Torrent Clients (Mainly use utorrent) but get the same error
If I cut & paste the torrent link directly into Client it works fine
Can You please help and find a solution
Thanks

**Comment by Mika-** [comment]
Couldn't test that with the latest utorrent as it's so full of spyware that windows prevents installing it. But atleast with version 2.2.1 it worked fine.
