### ISSUE TITLE
Failed to login in LibreWolf

### ISSUE THREAD

**Issue by istalker2** [Mika-/torrent-control#156]
Hello!

I cannot make torrent-control work properly in the LibreWolf (firefox clone) browser with ruTorrent. It used to work before though.
The problem is that I'm getting Failed to login error every time. It's for ruTorrent with basic HTTP auth. I installed the extension into plain Firefox, copied all the extension settings from the LibreWolf and it works there. I'm not a web developer, but I found how to inspect the requests made by the extension and could compare them. The difference is that in LibreWolf the request to add a torrent doesn't contain the `Authorization` header at all and therefore the server responds with 401. I tried to reinstalling the browser from scratch with all previous profiles deleted and without changing of the browser settings or adding any extensions, still with the same result. qBittorent server through the same instance works though so I believe the issue is specific to ruTorrent

**Comment by istalker2** [comment]
I'm new to JavaScript, but I put number of breakpoints into the source code to see how login and addTorrent work and from what I see `onAuthRequired` and `onAuthCompleted` are just not getting called

**Comment by istalker2** [comment]
found out the root cause. Older browser versions have network.auth.subresource-http-auth-allow set to 2 while updated version defaults it to 1. Setting it to 2 fixed the problem. Updates to other FF forks might have similar issues. I switched to Waterfox and the same problem happened there after upgrade from G5 to G6

**Comment by Mika-** [comment]
Kinda expected this to be configuration issue related to LibreWolfs hardenings.
