### ISSUE TITLE
[Feature Request] Add Synology Download Station as a client

### ISSUE THREAD

**Issue by tomck** [Mika-/torrent-control#164]
While there is an [existing extension to do this](https://github.com/seansfkelley/nas-download-manager), it does not pass along destinations like torrent-control does, so if you want to send different torrents to different directories that is not possible. While I can create a request on their page to do that, it feels like adding the API for Download Station may be simpler, especially for power users who may have multiple torrent client destinations already.

The [API documentation is available from Synology](https://global.download.synology.com/download/Document/Software/DeveloperGuide/Package/DownloadStation/All/enu/Synology_Download_Station_Web_API.pdf), it seems the Create command is what you would use.

Thanks!

**Comment by Mika-** [comment]
Synology Download Station is now available in the latest version. Hopefully it works
