### ISSUE TITLE
Chrome - Manifest V3

### ISSUE THREAD

**Issue by virtualbitzz** [Mika-/torrent-control#167]
I don't fully understand the implications of Manifest v3 for Chrome extensions. I'm using Torrent Clipper in Chrome that references this repo as the original author. Is it possible to create the functionality that this extension / plugin has in Manifest v3 at all? I'm trying to figure out if I need to make plans to start abandoning Chrome.

**Comment by Mika-** [comment]
In my understanding for this addon manifest v3 only limits the maximum amount of url catching rules
