### ISSUE TITLE
Add torrent (Paused) with qBittorrent v5.0.0: does not add as paused, starts downloading

### ISSUE THREAD

**Issue by junpet** [Mika-/torrent-control#168]
Using the option `Add torrent (Paused)` does not add torrent as paused, but starts downloading.
qBittorrent v5.0.0
Torrent Control v0.2.39

**Comment by Mika-** [comment]
qBittorrent made some changes to API unannounced in 5.0

**Comment by Mika-** [comment]
Support for qBittorrent 5 is now added

**Comment by imaginesoft** [comment]
hello, could it be this fix now changes the behavior on adding to previous qbit versions (such as that it doesn't respect the addon's paused setting (I have 'add torrents as paused' there but stopped working since this morning in both 4.5.5 instances i use)

**Comment by Mika-** [comment]
Yes. Choose older qBittorrent version from the bittorrent client selection. Clients without version indicator are always trying to be compatible with the latest version, so for the most people things just work as their apps update.
