### ISSUE TITLE
Adding torrent to transmission changes "X-Transmission-Session-ID" Header

### ISSUE THREAD

**Issue by canbaytok** [Mika-/torrent-control#169]
Hi there,
I recently switched to Firefox, because of upcoming ManifestV3 changes to Chrome and found this wonderful extension to add torrents quickly to my transmission instance, but unfortunately I noticed an issue.

I am using Firefox v131.0.3 (64-bit) and access my transmission instance via HTTPS from the world wide web (no local access). I also have a basic auth in place, that is configured in my nginx reverse proxy.
The issue I am having is the following:
The transmission instance can be accessed without any issues and I see a `X-Transmission-Session-ID` in the request headers, when the `/transmission/rpc` endpoint is called:
![image](https://github.com/user-attachments/assets/c4b5dc28-6cc4-48fd-ad18-bdd29ac4762e)

This `X-Transmission-Session-ID` headers changes however after adding a torrent with Torrent Control and reloading the transmission instance tab, resulting in an `409` response and the error message, that the header is invalid:
![image](https://github.com/user-attachments/assets/08d2b32c-8afe-4038-b215-7d8d0a8e3fd6)

![image](https://github.com/user-attachments/assets/2fb6c7fb-bff2-4fbd-ba3c-ae77390c9d52)

Oddly enough another call is made to the `/rpc` endpoint before the one that fails and the header is correct in this one and does not contain the `null` prefix, but no data is requested and the response is therefore `"no method name"`

The only way to access the transmission instance again is to disable the extension and reenable it, which releases the control of the header I guess and requests the `/rpc` endpoint with the correct session id.

Another solution I've found is to expose the transmission instance on a second subpath (`transmission2.domain.tld`) and use this as the target in the Torrent Control settings. Access via the first subpath is still possible, even after a torrent is added and the session id header is malformed.
It's not a perfect solution, but a viable workaround, in case this issue can't be fixed any other way (at least for me), but maybe the fix is straightforward and easily implemented

**Comment by Mika-** [comment]
There's been some wonkyness with Transmission sessions I haven't been able to reproduce. I refactored Transmission handling to prevent crosstalking betweend addons and users sessions that should fix these problems.

**Comment by canbaytok** [comment]
Hi there,
update is installed and the issue seems to be fixed.
Thanks a lot!
