### ISSUE TITLE
NetworkError when attempt to fetch resource. Deluge

### ISSUE THREAD

**Issue by DragooNick** [Mika-/torrent-control#17]
Clicking on magnet links or rightclicking and adding a torrent by torrent control throws me the error.
Connection to the server doesn't seem to be the problem as I get to the deluge web ui if I click on the tc button in the firefox menu.

**Comment by Mika-** [comment]
This error is generic low level network error from firefox. Check that your server address doesn't have any whitespace or other weird characters.
