### ISSUE TITLE
[feature request] Context menu -> Send torrent to : Server 1 or Server 2 or Server 3, etc.

### ISSUE THREAD

**Issue by Munkenmo** [Mika-/torrent-control#175]
A neat feature of Xirvik torrent addon, is the ability to send to different torrent clients direct from the context menu [(picture)](https://i.imgur.com/Er3gLt8.png).

Could this please be incorporated here?

**Comment by Mika-** [comment]
This is now available in the latest version.

![context menu](https://github.com/user-attachments/assets/bb65bb0e-5616-4747-aa76-a13aebe6d2da)
