### ISSUE TITLE
torrent files not catched

### ISSUE THREAD

**Issue by XinHong** [Mika-/torrent-control#177]
Hello all,

If I click on links like ***.torrent, Torrent-Control catches the file but if the link is like https://xxx/Download?UserId=xx&TorrentKey=xx Firefox shows me if I want to download the file to my computer or if I want to open it with an external software.

I tried to choose "open with Firefox" but the same panel opens (open with or download).

If I remember it was working few days ago, the option "Catch torrent URLs" is set and I tried to reinstall it.

**Comment by Mika-** [comment]
That url doesn't have clear indication about being a torrent url (.torrent extension etc), and it isn't in a format of any common torrent tracker software. So it hasn't never worked out of the box. Maybe the site changed it's url structure? For these site specific urls you can add a custom regular expression matcher in settings.
