### ISSUE TITLE
server.address/login is not a valid URL (WAN/Internet & qBittorrent 4.0.4)

### ISSUE THREAD

**Issue by Mistywing** [Mika-/torrent-control#19]
Hello.

This addon seems to have an issue when used through WAN/Internet with qBittorrent 4.0.4. 

It works fine if I attempt to use it on the local computer running the torrent client it is supposed to send things to. However by going through the internet it seems there is an issue of the addon trying to fetch a /login page from the server address field.

![image](https://user-images.githubusercontent.com/20234353/39398865-67f39154-4b0c-11e8-811d-827bfeb2265e.png)

This is despite the configuration amounting to the following, obviously with no /login entered in the server address field. Both LAN and WAN are configured the same way as I have a local DNS resolving the address of the server.

![image](https://user-images.githubusercontent.com/20234353/39398915-cec93eb0-4b0c-11e8-944d-fed9a840ab48.png)

The server address in both cases is in the format of:
`https://name.ddns.net:port/`

Using the dialog option instead of the right click contextual menu also results in the same pop up notification.

I should also note that clicking the icon of the addon in the customizeable toolbar does not open the WebUI on the WAN, but does on the LAN.

**Comment by Mika-** [comment]
I'm using the same setup myself and haven't encountered any issues. Error message looks like to be coming straight from the firefox url parser and is resulted when there's no valid hostname in url.
Are you using punycode or something other odd things in your domain?
You propably tried to copy'n'paste url to the address field and that worked?

**Comment by Mistywing** [comment]
I have disabled every extension except Torrent Control and it has successfully worked across WAN. I suppose now it is time to isolate to which extension. 

For information:
I have also copy and pasted the URL (before it was typed manually). There was no visible change or error between the two versions.
The URL entered links directly to the WebUI of qBittorrent, there is no code running on the domain.

I will come back with a reply of which extension if I find out. Please wait a moment.
