### ISSUE TITLE
Add support for qBittorrent 4.1.x

### ISSUE THREAD

**Issue by Ingvix** [Mika-/torrent-control#20]
I keep getting this message though I have checked my credentials many times. My client is v4.1.0alpha. What could be the problem?

**Comment by Ingvix** [comment]
I tried enabling bypassing authentication in IP subnet that I am and clearing username and password fields in addon settings but it's still giving the same error.

**Comment by Mika-** [comment]
qBittorrent 4.1 series will introduce a new customizable and more secure web ui. This will be supported when the API is finalized.

**Comment by Ingvix** [comment]
Oh, I see. Shouldn't have compiled the latest build then... Too lazy to downgrade so I guess I'll just stick with more manual torrent adding for now.
