### ISSUE TITLE
Doesn't work on a specific tracker

### ISSUE THREAD

**Issue by monkey113** [Mika-/torrent-control#21]
Hello Mika

I love Torrent Control and use it since release. Thank you for your work.

I joined a tracker that's relatively new and Torrent Control doesn't work there. It just says "Failed to read torrent" if I try to add one via right click. The admins don't really know what could be wrong tracker wise. I thought maybe you can tell us a bit more about this error or how we can get a bit more information. If I download the torrent and manually upload it to my Deluge WebUI it works without a problem. It also works on every other tracker I use without a flaw.

I can't really give you more infos on this now, but if you need further information I'll be glad to do more research.

Thanks in advance and have a nice weekend

![pic-55c42a55e0e4f55a0acf3feb03e8fdb4](https://user-images.githubusercontent.com/39196362/39933167-805af63e-5542-11e8-8375-458599752210.jpg)

**Comment by Mika-** [comment]
`Failed to read torrent` refers to an unrecognized mime type (other that `application/x-bittorrent` or `application/octet-stream`). This is used to sanity check that the thing we are trying to process is actually a torrent. Mime type is checked to get a proper error as many clients report failed torrent additions as succesfull.

You can check what mime type is returned via devtools > network > right clickin torrent link. Devtools will show the request and it's details.

**Comment by Mika-** [comment]
Good that it helped. There's propably a lot of other misconfigured servers that give other exotic mime types, so i'll make the error more verbose.
