### ISSUE TITLE
Connecting with username and Deluge

### ISSUE THREAD

**Issue by maiki** [Mika-/torrent-control#24]
Hiya! When I select Deluge from client list the username becomes locked.

![screenshot from 2018-06-15 15-45-52](https://user-images.githubusercontent.com/74557/41492343-65fcf0ee-70b3-11e8-9a72-b353fc38ebd1.png)

I glanced at `deluge.js` and of course have no idea what I am looking at, but I noticed no mention of username.

I am new to using deluge on local network (but thanks, I've used your plugin with qBit for months!), and have always connected with `deluge-console`. That requires [a credential in `auth`](https://dev.deluge-torrent.org/wiki/UserGuide/Authentication).

I notice there is also a [web UI](https://dev.deluge-torrent.org/wiki/UserGuide/ThinClient#WebUI), a separate web daemon that connects to `deluged`.

Okay, am I missing something? I am not sure how to connect without a username. I tried `maiki@192.0.2.0:58846`, with and without `http://`, etc. Regardless of what I try I get, `Server address is invalid`.

Is the `web UI` required for the add-on to connect?

**Comment by Mika-** [comment]
Yes, you need the web ui module, which provides web interface and functionality.
