### ISSUE TITLE
Add an option to toggle "Catch torrents url" on icon click

### ISSUE THREAD

**Issue by Delgan** [Mika-/torrent-control#26]
Hi.

What do you think of adding an option so that clicking on the Torrent-Control icon in the navbar would enable / disable catching torrents urls?

That would be very convenient (this was how Bittorrent WebUI extensions worked in Firefox < Quantum), because some time I need to download a bunch of torrents to me seedbox so I would like to avoid using the context menu, and sometimes I just want to download the torrent on my local computer and I would prefer to avoid going through the Torrent-Control settings just to switch the "catch torrents url" option.

So this would just be one-click to alternate between the two downloads mode.

(Btw I already said it but your extension is super useful, thanks!)

**Comment by Mika-** [comment]
This is actually the next item on my backlog. The plan is to add a setting for browser action to what to do.

**Comment by Mika-** [comment]
I have this functionality implemented, but currently Firefox apis don't allow proper icon changes if icon is dark/light themed. So it's impossible to add proper icon hint for catching state.
I can add option for toggling to the context menu next to Settings. Does this work for your use case?

**Comment by Delgan** [comment]
@Mika- Thanks for having taken care of this!

Too bad that Firefox shows once again its limits for the development of extensions... 😞 

But your workaround seems fine!
