### ISSUE TITLE
TypeError:

### ISSUE THREAD

**Issue by StGabriel1** [Mika-/torrent-control#27]
Gday

When trying to add a magnet link with a previous add on, i started getting an error "TypeError: NetworkError when attempting to fetch resource" Nothing changed with browser/password/URL that I know of to have caused it. Ditched that add on and installed Torrent-Control and still get the same error trying to add torrents to my media PC. 
Site is Pirate Bay if that matters
FF 61.0.1
Windows 10 Home

**Comment by Mika-** [comment]
That's a generic ajax error that Firefox throws when it encounters an network error, timout, etc.
You are right that error message should indicate better which action fails and why. I'll add this enhancement to backlog.

**Comment by StGabriel1** [comment]
Any ideas where how i should proceed to rectify? I know its not a network issue as both PC's can see each other.

**Comment by Mika-** [comment]
Which torrent client and version are you using? As this maybe related to some update.

**Comment by StGabriel1** [comment]
utorrent ver: 3.5.3 (build 44494)

**Comment by Mika-** [comment]
Tested against newest version and it works fine. Make sure you are using the right port, there's also IP whitelist in uTorrents side. You propably can access web ui via browser?

Btw uTorrent installer looks like to be fiddling with firewall rules and doing all kinds of shady things, so I'm not surprised if something goes wrong there.
