### ISSUE TITLE
Cannot add torrent from context menu in a private window

### ISSUE THREAD

**Issue by ExplodingLemur** [Mika-/torrent-control#29]
When I right-click a torrent in a private browsing window and select "Add torrent" I get an error "Failed to fetch torrent. (404: Not Found)"  I'm using this with Deluge v1.3.15.

**Comment by Mika-** [comment]
Addon operates in spanning mode, so there's no difference between normal and private browsing.

**Comment by ExplodingLemur** [comment]
Is there any debug logging I can enable that might help ID the root cause?  Does it grab the .torrent file to a temporary location and then upload it to the configured client, or does it pass the URL of the .torrent file to the configured client directly?  (The latter might hit issues when the .torrent is behind an authN/authZ gateway, and the session state is not accessible to the client)

**Comment by Mika-** [comment]
You can attach debug tools by `Menu > Add-ons > *Gear* > Debug Add-ons` check `Add-on debugging` and select `Debug` on Torrent control. This opens Firefox devtools attached to the addon. You are most likely interested in Network tab as that will show the torrent fetching request.

Addon fetches torrents to local cache as this way we can send cookies to authenticate.

**Comment by ExplodingLemur** [comment]
Thank you.  The cookie that TorrentControl is sending is from my non-private browsing session (If I visit the site from a non-private session, it's the same cookie ID that TorrentControl sends when it tries to download the torrent file).  Requests to the site from the private session has a different cookie.

**Comment by Mika-** [comment]
This maybe related to the fact that Firefox runs all addons in spanning mode and therefore may have limited access to page context in incognito. Fix to this could be to move torrent fetching inside content script and use new page context fetch method.

**Comment by hevisko** [comment]
Same problem in FireFox 62.0 (64-bit) on MacOSX to Transmission. Only now saw this, so I'll close #38 

Private tracker, so yes, I suspect/guess the necessary cookies/authentications wasn't done ;(

**Comment by Mika-** [comment]
Took a look into this and it looks like there's currently no way to access private windows context to get the cookies. So for now we can just wait for api improvements.
