### ISSUE TITLE
Support for directories

### ISSUE THREAD

**Issue by gasparov** [Mika-/torrent-control#30]
Hi,
   any possibility to get support for directories? Remote torrent adder for chrome allows to write down a list of directories where you want your torrent to be saved. When it catches a torrent a window popups and asks in which directory you want your torrent saved. 
Best Regards and Thank You

[https://github.com/bogenpirat/remote-torrent-adder/blob/master/webuiapis/ruTorrentWebUI.js](url)

**Comment by Mika-** [comment]
Directories, labels and adding in paused state are in plans. The biggest problems are the need of user interaction and complex selectors/validators for directories and labels.

**Comment by annomatik** [comment]
And please also, if possible, add qBitTorrent categories. For me, it would be perfect, if there was a popup only asking for a category -- maybe, that can be customizeable via settings?

**Comment by Mika-** [comment]
Categories/labels will be supported. I actually already did some work on [other branch](https://github.com/Mika-/torrent-control/tree/client-capabilities).
Plan is to add couple of extra options to context menu. And propably a setting to always prefer advanced popup.
![](https://i.imgur.com/RPlsMse.png)

**Comment by kocane** [comment]
@Mika- first off; thanks for making this addon, glad there's someone doing it since the other alternatives for Firefox doesn't seem to work as good as this one.

As for labels - I'm using Deluge .. could it be possible to just manually define labels inside the addon settings and then have these be presented as a sub-contextmenu for torrent control?

**Comment by Mika-** [comment]
Support for labels via context menu is now available in the latest version.

**Comment by kocane** [comment]
@Mika- Hmm. I updated the addon but I don't see any sub-contextmenu :-/?  Just a single "Add torrent" button. I added some labels, but it's the the same.

Also, I'm using Deluge behind a reverse proxy that has basic auth enabled.
Is there any way to use this addon with this, yet?

**Comment by Mika-** [comment]
@kocane Sorry didn't notice you were using Deluge. Deluge is currently lacking all the extra capabilities as I haven't found any documentation for the api. Maybe it's just time to read trought the Deluge source...

**Comment by adamwinn** [comment]
What about directories for rutorrent?

**Comment by almet** [comment]
Hi, thanks for the hard work here. I would really be happy to see a support for directories in ruTorrent. If you've added the support for labels, I believe it shouldn't be more complicated than that?

**Comment by almet** [comment]
After some quick look at the code, it seems that it's "just" lacking an UI, and that the code is already almost ready to support directories. Let me know if there is anything I can help with.

**Comment by almet** [comment]
Neat, thanks!
