### ISSUE TITLE
Clarify the support of Deluge GTK and web client

### ISSUE THREAD

**Issue by krichter722** [Mika-/torrent-control#33]
It'd be nice to see the difference of Deluge GTK and web client reflected in the labels of connection types in the add-on configuration. The initial port 8112 and the inavailability of a username field makes me think that the support is for Deluge web, however it'd be nice if it was just clear.

**Comment by Mika-** [comment]
You are right that Deluge is very confusing with it's rpc communication architecture. Maybe `Deluge (Web UI)` as a label would be a bit more describing?
