### ISSUE TITLE
Error when adding magnet link to rutorrent

### ISSUE THREAD

**Issue by llucax** [Mika-/torrent-control#34]
Hi, I'm trying out this add-on but I get an error when using it with a rutorrent hosted in seedbox.io.

![image](https://user-images.githubusercontent.com/1031485/44955717-361ebe00-aeb8-11e8-9ed9-e92bf34b1662.png)

rtorrent version: 0.9.6/0.13.6 (not sure if the rutorrent version is the same or part of it).

Let me know if you need more info.

**Comment by Mika-** [comment]
There's really no way to tell which version of rutorrent you are running as it's mostly rolling update novadays. I checked rutorrent commits related to magnet handling and didn't notice any affecting changes in a past year.

Do normal torrents work properly? If not, this maybe related to vendors authentication system.

**Comment by Yoposoc** [comment]
I have this issue too with Flood. I installed flood via quickbox.

**Comment by llucax** [comment]
Different error but still an error with a torrent file:

![image](https://user-images.githubusercontent.com/1031485/45559733-95c78280-b843-11e8-94c1-861eb802f6a6.png)

**Comment by Yoposoc** [comment]
I get errors like this: ![nbudiqayxhli_2018-09-20_09-59-07 1](https://user-images.githubusercontent.com/2718371/45834401-db5cd300-bcbb-11e8-9b7f-9c8c600758b4.jpg)
![zkt4uss5rthi_2018-09-20_09-59-35 1](https://user-images.githubusercontent.com/2718371/45834409-e7489500-bcbb-11e8-8872-535829d5b3e4.jpg)

**Comment by Mika-** [comment]
The latest version now outputs failing json response to make debugging easier.

**Comment by 07416** [comment]
> 
> 
> Different error but still an error with a torrent file:
> 
> ![image](https://user-images.githubusercontent.com/1031485/45559733-95c78280-b843-11e8-94c1-861eb802f6a6.png)

You should have typed the error in order for it to be indexed in search:

`Unknown response. (405: Not Allowed)`

**Comment by llucax** [comment]
Hi, after a long while since the last time I tried torrent-control, I gave it another shot and I'm still experiencing this problem, even with the latest version (0.2.12 according to https://addons.mozilla.org/en-US/firefox/addon/torrent-control/).

The error is actually worse than before, as there is no information at all but the name of the server as I configured it plust "box".

![image](https://user-images.githubusercontent.com/1031485/64734105-46fc0980-d4e6-11e9-9237-aa93b4aa66bc.png)

Any ideas about how to continue?

**Comment by Mika-** [comment]
Your seedbox provider most likely implements custom made authentication or otherwise modified version of rutorrent.
Invidual providers are hard to support as you need to subscribe the service to debug and examine what changes are needed.

**Comment by llucax** [comment]
Hi, thanks for the reply but even then, should I get a readable error message so I can debug it myself? Authentication should not be the problem as it uses regular http Auth.

On 15 September 2019 10:38:18 GMT+02:00, Mika Simanainen <notifications@github.com> wrote:
>Your seedbox provider most likely implements custom made authentication
>or otherwise modified version of rutorrent.
>Invidual providers are hard to support as you need to subscribe the
>service to debug and examine what changes are needed.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Mika-/torrent-control/issues/34#issuecomment-531546529

-- 
Leandro Lucarella (luca)
Sent from my phone. Please excuse my brevity and any typos.

**Comment by UntouchedWagons** [comment]
I submitted a support ticket to SeedBox.io regarding this issue and this is the response I got:

>Hi,
>
>We have heard this recently, it appears that a recent update to firefox has broken this plugin, the only solution seems to be to downgrade to an earlier version of firefox.
>
>Best regards,
>Daniel Walker
>Hostingor LTD

Mika any idea what changes Daniel might be alluding to?

**Comment by Mika-** [comment]
Could this seedbox.io issue be duplicate of #71? There hasn't really been any extension related Firefox changes in months.

**Comment by UntouchedWagons** [comment]
Yup, adding `/rutorrent/` to the end of the server address does the trick.

**Comment by llucax** [comment]
Works for me too! Finally! Thanks! It would be great if this can be documented somehow, or even auto-detected by the extension and suggested to the user or something, or at least, once more, improve the error message so it's easier to know where the problem lies.

**Comment by llucax** [comment]
Now I have only one remaining issue, the labels don't seem to be set as configured. Any ideas about that?
