### ISSUE TITLE
customise torrent url catch regexp

### ISSUE THREAD

**Issue by tengmalm** [Mika-/torrent-control#37]
I was confused why catch torrent urls option didn't work sometimes. but I found on #10 it said webextension doesn't allow mime intercept just check regexp for `href="*.torrent"`

could you pls add a custom option to add new regexps? so for sites with `torrent.php?id=12345` it can still work

**Comment by Mika-** [comment]
Do you know which tracker software uses that url schema? `torrent.php?id=12345` feels a bit too generic to support straight ahead, as it may break many sites with false positives.

**Comment by mynameisbogdan** [comment]
Maybe adding a field in the options, where you can add a regex per line so an user can add on their own terms?

```
^https?:\/\/(www.)?HOST\/torrent\.php\?id=\d+$
^https?:\/\/(www.)?HOST\/torrent\/\d+$
^https?:\/\/(www.)?HOST\/download\.php\?id=\d+$
```

**Comment by Mika-** [comment]
I'd rather not add a setting that would be removed when the content handler api becomes available.

**Comment by fsign** [comment]
Hi Mika, Here is a torrent url that fails

www.myanonamouse.net/tor/download.php/LONGSTRINGOFCHARACTERS

**Comment by fishpen0** [comment]
Another URL that fails:
https://animetorrents.me/download.php?torid=LONGSTRINGOFCHARACTERS
