### ISSUE TITLE
Wrong username or password

### ISSUE THREAD

**Issue by jokerby** [Mika-/torrent-control#4]
Clean qBittorrent (with -nox package) install with no matter which password.
Without any problem log in to webui, but cannot add torrent file by extension getting error in title.
Configuration is:
server address: http://192.168.5.222:8080/gui/
Username: admin
Password: adminadmin | secret | password

If change address to http://192.168.5.222:8080/ - getting error "Failed to add torrent"

OS: CentOS 7
qBittorrent: 3.3.7

**Comment by Mika-** [comment]
http://192.168.5.222:8080/ is the right one.
qBittorrent 3.3.7 is pretty old and is already 4 api version behind. New versions have better security, so I don't see a point supporting the old ones.

**Comment by fliker09** [comment]
It's all good and shiny till you try to use ARM machines as the one running qBittorrent. In my case it's Odroid-C1 with Ubuntu 16.04. In its repos you can find only 3.3.1. There is PPA but it doesn't have builds for armhf... Any chances to get support for older versions?

**Comment by Mika-** [comment]
Official repositories lagging behind is actually a valid reason to support some backwards compatibility. I have a hunch about what could cause the api missmatch which I will check.

**Comment by Mika-** [comment]
This should be fixed in the latest release (0.1.3). the older versions of qbittorrent didn't support login form as multipart.

**Comment by fliker09** [comment]
All good, working without a hitch, thanks!
