### ISSUE TITLE
Can't change server through configuration

### ISSUE THREAD

**Issue by ziffusion** [Mika-/torrent-control#40]
I have two servers defined in the configuration, but I don't seem to be able to use the second server. I have tried changing the server - and then (a) reloading the tab (b) restarting the browser.

This is on Firefox 62.

**Comment by Mika-** [comment]
You can change server by right clicking the icon on browsers top bar.

**Comment by ziffusion** [comment]
Thanks! That works.

**Comment by ziffusion** [comment]
A couple of suggestions though.

1. The drop down in configuration labeled "Current Server" is a little confusing. Seems to imply (at least to me) that you are setting the current server - instead of merely picking it for editing. Maybe consider a different label? Just "Server" might even be OK.

2. A small note might help too, directing the users to set the current server by right clicking the Addon button.
