### ISSUE TITLE
Roll back to previous version? (or a minor adjustment suggestion)

### ISSUE THREAD

**Issue by Garbonzo17** [Mika-/torrent-control#41]
I understand this is free, and it is by far the best thing to use on Firefox, but since I am using a split-tunneled VPN where the torrents are using a VPN, but my browser isn't always, this plugin has always and still is a perfect work-around. 

I don't know how to do it from source, but I'd prefer to go back to the version were the context menu doesn't have the tree expand with the new Add Paused. 
I understand how that could be useful to some, but it isn't for me, and after trying for a full month, I still sometimes miss/forget it and just click on the Torrent Control (in the right click context menu). 

I had hopped in the settings I could disable the new tree... not just uncheck the "add torrent (paused" and leave the "add torrent" as a single item on the tree... I am talking about reverting to the old single item if you choose to remove the (paused) option via some type of checkbox on the options page.  
Again, I am completely happy to just uninstall v0.23 and reinstall the version prior to this multi-option, whatever is easier.., if nobody else is bothered by the tree, then I am fine staying on the previous version.
Lastly, what exactly is the check box for  "Catch Torrent URLs" ?  I can't find help info anywhere on what that actually does. I can only assume it has something to do with that line about uTorrent, but with me using qBittorrent I haven't seen any effect.

**Comment by Mika-** [comment]
Firefox Addons [hosts all past version](https://addons.mozilla.org/en-US/firefox/addon/torrent-control/versions/) so you can install it from there.

Massive multi level context menus are a big problem with allmost all extensions, as web extensions api currently requires user interaction for many basic things.
Current idea is to extend context menu setting with an extra option "simple". This would limit context menu to one level.

`Catch torrent URLs` enables url monitor which catches and adds all matched torrents automatically on left click. As we need to match url strings, we need to specify all of them beforehand. Currently we are matching all urls ending with ".torrent" and urls from a popular tracker software Gazelle (`torrents.php?action=download&id=\d+`). This whitelist will be user editable in some point, as many sites have their own url schemas that can't be recognized automatically.

**Comment by Mika-** [comment]
New release now has an option to use simplified context menu.
