### ISSUE TITLE
can you add an option to add torrent (or magnets) in paused mode?

### ISSUE THREAD

**Issue by rezad1393** [Mika-/torrent-control#43]
this will make managing the torrents easier.

**Comment by Mika-** [comment]
This is already widely supported. Last two clients missing this are Tixati, which will get support in a next release. Other one is uTorrent which is a huge pain to test as most of the userbase is running ancient versions.

**Comment by rezad1393** [comment]
??
for magnet and torrents by default as an option in the addon.
I use rutorrent and when I just click on a magnet or torrent they get added in the downloading mode.
I want them to be added in paused mode.

**Comment by rezad1393** [comment]
??
for magnet and torrents by default as an option in the addon.
I use rutorrent and when I just click on a magnet or torrent they get added in the downloading mode.
I want them to be added in paused mode.
