### ISSUE TITLE
"http://username:password@host/subpath/json is an url with embedded credentials" for Deluge-WebUI

### ISSUE THREAD

**Issue by Cediddi** [Mika-/torrent-control#44]
Hi. I have a deluge install behind a nginx with http basic auth (scaleway default torrent server) and I want to connect to the deluge webui with http basic auth. Because I couldn't find a way to define basic auth, I put the credentials in the url but the plugin is complaining about that.

I think plugin should support basic http auth with url params.

**Comment by Mika-** [comment]
Http auth isn't supported for deluge, but this is a clear use case as deluge itself only supports wonky password only authentication.

**Comment by Cediddi** [comment]
Wow, thanks man. Yeah, putting my web ui behind basic auth is what I do for years (I used to use transmission, now switched to deluge, as well as webui-aria2c)
