### ISSUE TITLE
When adding a torrent on some sites, it doesn't auto add

### ISSUE THREAD

**Issue by SpacePotatoBear** [Mika-/torrent-control#45]
When on certain sites, when right clicking download, it doesn't auto add to the client. One must left click and select add on the download link.

this only occurs on certain sites.

**Comment by Mika-** [comment]
Addon detects torrents by matching strings in an url. Current rules need url to end with `.torrent` or include Gazelles url schema `torrents.php?action=download&id=\d+`.
Torrent detection will be rewritten when content handler api lands somewhere around Firefox 65. Meanwhile I can add more rules to handle common tracker applications.

**Comment by SpacePotatoBear** [comment]
> Addon detects torrents by matching strings in an url. Current rules need url to end with `.torrent` or include Gazelles url schema `torrents.php?action=download&id=\d+`.
> Torrent detection will be rewritten when content handler api lands somewhere around Firefox 65. Meanwhile I can add more rules to handle common tracker applications.

The site in question is animebytes which from my understanding uses Gazelle under the hood.

they take the format of 
https://animebytes.tv/torrent/393658/download/<super secrete passkey> 

and resolve to a .torrent file.
