### ISSUE TITLE
Unknown response. (404: Not Found) while sending magnet link to qBittorrent v3 webui

### ISSUE THREAD

**Issue by proba0** [Mika-/torrent-control#48]
Hi,

I just installed the extension and wanted to test it with my qBittorrent setup and ended up with this error message.

The reason for it is probably because the version of qBittorrent on my Debian 9 (Stretch) box is 3.3.7. There are no newer versions available for that platform (it is my current Raspberry Pi installation).

Could you please introduce an additional"client" in your add-on? Something like "qBittorrrent v3" and adapt the code to the APIs of v3? It would help a lot.

Thanks in advance!

**Comment by Mika-** [comment]
There already is an additional client for legacy qBittorrent versions. It's marked as qBittorrent <=4.0.4 as that was the point where the web api was updated.
