### ISSUE TITLE
Add torrent to ruTorrent with both a label AND path

### ISSUE THREAD

**Issue by damagu** [Mika-/torrent-control#49]
I was previously using Remote Torrent Adder on Chrome which gives users the ability to select both a path AND a label when adding torrents to ruTorrent. 

I also add torrents to ruTorrent by uploading them from my local machine to a `~/watch/` directory on my seedbox and I have ruTorrent's AutoWatch feature set to add torrents with a label matching the name of the subdirectory it finds them in within the `~/watch` directory. For example, when ruTorrent finds a torrent file in `~/watch/tvshows/`, the torrent is added with the label _"tvshows"_. ruTorrent then  uses the label _"tvshows"_ to set the download path as `~/seeding/tvshows/` and, when download is complete it copies the files to `~/done/tvshows/`.

I know that with Torrent-control, I can use the options "add torrent with label" OR "add torrent with path" but there doesn't appear to be a way to select a label AND a path when adding a torrent to ruTorrent. When I use "add torrent with label" option, the torrent gets added with that label but the files don't get saved to `~/seeding/[label]/` they just save to `~/seeding/`. And when I use the "add torrent with path" option with the path set to `~/seeding/tvshows/`, the ruTorrent AutoTools feature doesn't add a label based on the path and it doesn't send a copy to `~/done/tvshows/`.
 
Can someone tell me:

1. Is it possible to configure Torrent-control so that I can select a label AND a path when sending torrent's to ruTorrent?
2. If Torrent-control can't do this, is it possible to set Torrent-control so that it saves torrents without adding them? This would allow me to save them to my `~/watch/` directory and then I can let ruTorrent's Autotools add the torrent, label and set the path to download and copy to.
3. Alternatively, if Torrent-control can't be set to just save and not add, does anyone know if Autotools can be configured to set a torrent's:
    - path based on the label selected in Torrent-control 
or 
    - label based on the path selected in Torrent-control?

Any help would be appreciated.

**Comment by Mika-** [comment]
1. As path support just landed, there's no support for label + path combinations yet. I have done some testing with advanced add dialog, but it's implementation is unsure as content handler api isn't supported yet in firefox.
2. ruTorrent doesn't have that kind of functionality.
3. I'm no fully sure. But if you can use directory name as a label, then autotools may work for you by combining autolabel and automove. One other way could be just running a bash script when a download finishes.

**Comment by adamwinn** [comment]
I'd love to see a label + path option too

**Comment by sun1ight** [comment]
still waiting...
