### ISSUE TITLE
Does not appear to do anything

### ISSUE THREAD

**Issue by necromancyr** [Mika-/torrent-control#5]
Just installed and while config works, no icon is appearing to add to the toolbar and just a save dialog is opening when torrents links are clicked.  If I select "Add Torrent" from right click menu, I get a failed to read torrent error.

**Comment by Mika-** [comment]
There's no toolbar actions yet. Long term goal is to add status popup with complete overview to torrents. I will add temporary solution as action button to open the web interface in coming weeks.

Failed to read torrent means that server responded with other file type than application/x-bittorrent. Response is most likely application/octet-stream which is default type for miss configured servers. I will add support for that in next update.

**Comment by Mika-** [comment]
Support for torrents with mime application/octet-stream is now available in the latest update.

**Comment by necromancyr** [comment]
Still getting the  failure to read torrent error on multiple trackers.  Not sure if it's because I have torrent files associated with an app or what - but definitely not working.  (The right click menu item is a nice add!)

**Comment by Mika-** [comment]
Mime type is most likely something else. You can track this in more detail in issue #7
