### ISSUE TITLE
[Bug] qBittorrent 404 Error

### ISSUE THREAD

**Issue by zero77** [Mika-/torrent-control#50]
When trying to test the connection or send torrents to qBittorrent it doesn't work and instead gets a 404 error.
I think this maybe because qBittorrent nightly has dropped support for their old API.

Also, i am using the most up to date vershon of torrent-control.

> HTTP request failed: [404:NotFound] [POST] at [http://163.172.39.74:9000/login]

API Documentations:
https://github.com/qbittorrent/qBittorrent/wiki#webui-related

**Comment by Mika-** [comment]
There's support for both api versions. Different versions are shown as different applications `qBittorrent` for current and `qBittorrent (<=4.0.4)` for legacy.

**Comment by zero77** [comment]
I missed that, thanks.
Also, it may be worth removing legacy support.

**Comment by Mika-** [comment]
I'd like to remove it, but many linux distros are lagging way behind in versions.
