### ISSUE TITLE
[Feature Request] Optional Clipboard Monitor

### ISSUE THREAD

**Issue by zero77** [Mika-/torrent-control#52]
Can you please add optional (with enable option) clipboard monitoring particularly for android support.
For example, if any magnet links or links ending in .torrent are found within the clipboard then send them to the torrent client.
Thanks

**Comment by Mika-** [comment]
This could be one alternative to content handlers if mozilla still delays implementing them.

**Comment by Mika-** [comment]
Closing as unfeasable. Automated clipboard reading is considered as bad practise and has security implications
