### ISSUE TITLE
"null" auto-populating - flood

### ISSUE THREAD

**Issue by TimCook1** [Mika-/torrent-control#53]
When adding torrents to flood, the extension is automatically trying to place new torrents into the directory "null" by default with a tag of "null".  This causes the torrents not to start.  I would expect the default behavior to be no tag at all if I don't specify a tag, and the default directory if I don't specify one.

**Comment by TimCook1** [comment]
Someone correct me if I'm wrong at what I'm seeing - it would appear in index.js, you're setting the path and label to null by default:

https://github.com/Mika-/torrent-control/blob/653539b5eb1dd02a7ade042cab305cf9abffc19a/src/index.js#L37-L42



But in the actual flood.js there's no logic to say if the value is null, just don't use it, as such it turns "null" into a string and supplies that as the destination and tag:

https://github.com/Mika-/torrent-control/blob/653539b5eb1dd02a7ade042cab305cf9abffc19a/src/lib/flood.js#L52-L58

**Comment by Mika-** [comment]
Looks like I forgot that FormData turns null to "null" when casting to string instead of empty string.
