### ISSUE TITLE
What does the "catch torrent URLs" setting mean?

### ISSUE THREAD

**Issue by 07416** [Mika-/torrent-control#55]
Is the setting only for magnet link support? 

RuTorrent can already be associated with magnet links so personally I may want to disable the setting.

**Comment by Mika-** [comment]
It's for catching urls that are on [whitelist](https://github.com/Mika-/torrent-control/blob/master/src/util.js#L145-L155). Better catching will be implemented when Firefox supports content handlers.

Magnet protocol handler cannot be managed via extension, so you need to manage that via browsers own association settings.
