### ISSUE TITLE
Supported RTorrent version

### ISSUE THREAD

**Issue by 07416** [Mika-/torrent-control#56]
Does the addon support RTorrent/libTorrent version 0.9.7/0.13.7, 0.9.6/0.13.6, or both (through RuTorrent of course)?

I get `405: not allowed` error when adding a torrent, addon configuration in about:addons is entirely correct as far as I can see.

**Comment by Mika-** [comment]
Both versions are supported and I'm using latest myself.

`Not allowed` comes from POST request failing. Most likely indicating that configured server address is pointing to a wrong directory.
