### ISSUE TITLE
[Feature Request] Notification that torrent was added successfully or returned an error

### ISSUE THREAD

**Issue by BristleBeard** [Mika-/torrent-control#60]
It would be nice if on adding a torrent a notification would pop up saying it was added successfully, or an error message if failed due to your URL being down, bad password, etc.

**Comment by Mika-** [comment]
This feature has been supported from the first version. Are you not seeing those?
![](https://addons.cdn.mozilla.net/user-media/previews/full/194/194098.png)

**Comment by BristleBeard** [comment]
No, so far I've seen nothing. Firefox isn't showing any notification like that at all. I checked my notification settings, and I have them enabled, and nothing is blocked from showing them. This is using Win10 1903 as well.

**Comment by simonbcn** [comment]
To me works well on Arch Linux with Firefox 68.
