### ISSUE TITLE
[FR] Simple context menu not so simple when labels exist

### ISSUE THREAD

**Issue by simonbcn** [Mika-/torrent-control#61]
I use this extension with `qBittorrent` and I've defined labels in program and extension.
If someone sets labels in this extension, it's because he/she/... wants to use them. The "_Default_" menu is not practical because it shows them in a _sub-sub-menu_. And the "_Simple_" menu is too simple because it doesn't show any labels.
I think that if I select "_Simple_" as the context menu and have defined labels, it should show something like this (_these are the labels defined by me_):

![captura_20190715_123507](https://user-images.githubusercontent.com/428231/61210703-9f3ca800-a6fd-11e9-947a-fff7ac9c549a.png)

**Comment by simonbcn** [comment]
I have created a pull request with the modifications:  https://github.com/Mika-/torrent-control/pull/62

**Comment by Mika-** [comment]
That's propably a good middleground between features and complexity. I'll also add support for directories:

![tc](https://user-images.githubusercontent.com/5081253/61302821-1a31bb80-a7ef-11e9-9c97-28e6407bb139.png)

**Comment by Mika-** [comment]
This is now included in version 0.2.10
