### ISSUE TITLE
Cannot add torrent from private tracker when using containers

### ISSUE THREAD

**Issue by GodKratos** [Mika-/torrent-control#63]
I've just installed this addon and I'm getting the error "Failed to fetch torrent (404: Not found)" when trying to send a torrent from a private tracker.
It is similar to issue #29 but I'm not in private mode, instead I use firefox containers and I suspect the cookie is not being loaded from the container that is trying to send the link.

I have tested that it works OK if I use a new tab that is not in a container but all my private trackers I load in containers so it would be great if you could get that to work properly.

**Comment by Mika-** [comment]
Firefox Multi-account containers need explicit support from extensions. Adding support for this shouldn't be hard, and it propably fixes #29 as byproduct.
