### ISSUE TITLE
Regression from simple context menu

### ISSUE THREAD

**Issue by psychopathio** [Mika-/torrent-control#64]
with the new update the plugin no longer works on latest firefox  68., I cant click on it or use the magnet downloader

**Comment by jaypan** [comment]
Yes, it's broken for me now as well.

**Comment by Mika-** [comment]
Looks like Firefox >=68 prefers to autoselects externals applications (Transmission, qBittorrent, etc.) as default magnet handlers instead of asking. You can edit this in `Options > General > Applications`.

**Comment by psychopathio** [comment]
the icon on the top doesn't open the remote GUI anymore, I have 2 torrent clients located on one of my servers on the network & I rely on your plugin for adding torrents remotely.
Currently it will only work if I remove the plugin, add it again and configure it. but when I close the browser & reopen it the plugin wont work anymore.

**Comment by jaypan** [comment]
I am seeing the same as pshycopatheio. The toolbar icon no longer launches the GUI, nor am I able to add torrents. The contextual menu link is still there, but clicking it results in no message, error or otherwise, and the torrents are not added on my remote machine.

**Comment by Mika-** [comment]
Haven't been able to replicate this on any of the Firefox versions or in Edge.
What does the debug log say? It's at `Menu > Add-ons > *Gear* > Debug Add-ons > Inspect` on a `Console` tab.

**Comment by jaypan** [comment]
I'm seeing these two items repeated multiple times:

Error: Could not establish connection. Receiving end does not exist. 8 h0-main.js:1:158837
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. background.js:1
    sendRequestToSpecificTab moz-extension://97c89a9b-bff0-8f48-a8e9-d212113025bd/js/background.js:1

**Comment by jaypan** [comment]
Actually got this too:

e is undefined h0-main.js:1
    537 moz-extension://86194ee1-082d-394b-8559-e9142cf55202/h0-main.js:1
    apply self-hosted:4417
    applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:539
    wrapPromise resource://gre/modules/ExtensionCommon.jsm:752
    withLastError resource://gre/modules/ExtensionCommon.jsm:676
    wrapPromise resource://gre/modules/ExtensionCommon.jsm:744
Unchecked lastError value: Error: Invalid window ID: 91 h0-main.js:1
    537 moz-extension://86194ee1-082d-394b-8559-e9142cf55202/h0-main.js:1

**Comment by psychopathio** [comment]
just a side note, I use reverse proxy to access my torrent client on the server & remotely.

proxy.register has been deprecated and will be removed in Firefox 71. background.js:89
proxy.unregister has been deprecated and will be removed in Firefox 71. background.js:101
    makeError resource://gre/modules/Schemas.jsm:459
    logDeprecation resource://gre/modules/Schemas.jsm:1109
    checkDeprecated resource://gre/modules/Schemas.jsm:1121
    stub resource://gre/modules/Schemas.jsm:2333
    unregisterProxyScript moz-extension://2e09beeb-7363-498d-a7b0-63ea33a090e4/scripts/background.js:101
    setDisabled moz-extension://2e09beeb-7363-498d-a7b0-63ea33a090e4/scripts/background.js:192
    sendSettingsToProxyScript moz-extension://2e09beeb-7363-498d-a7b0-63ea33a090e4/scripts/background.js:136
    <anonymous> moz-extension://2e09beeb-7363-498d-a7b0-63ea33a090e4/scripts/background.js:249
Error: Could not establish connection. Receiving end does not exist. background.js:204:21
Error: Could not establish connection. Receiving end does not exist. 2 background.js:198:21
Error: Could not establish connection. Receiving end does not exist. background.js:204:21
<source> element has no “src” attribute. Media resource load failed. 2 popup.html
All candidate resources failed to load. Media load paused. 2 popup.html
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. common.js:4539
<source> element has no “src” attribute. Media resource load failed. 2 popup.html
All candidate resources failed to load. Media load paused. 2 popup.html
TypeError: can't access dead object

<source> element has no “src” attribute. Media resource load failed. 2 popup.html
All candidate resources failed to load. Media load paused. 2 popup.html
<source> element has no “src” attribute. Media resource load failed. 2 popup.html
All candidate resources failed to load. Media load paused. 2 popup.html
TypeError: Argument 1 of PrecompiledScript.executeInGlobal is not an object.
ExtensionContent.jsm:490:25
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 3 common.js:4539
<source> element has no “src” attribute. Media resource load failed. 2 popup.html
All candidate resources failed to load. Media load paused. 2 popup.html
<source> element has no “src” attribute. Media resource load failed. 2 popup.html
All candidate resources failed to load. Media load paused. 2 popup.html
TypeError: Argument 1 of PrecompiledScript.executeInGlobal is not an object.
ExtensionContent.jsm:490:25
<source> element has no “src” attribute. Media resource load failed. 2 popup.html
All candidate resources failed to load. Media load paused.

**Comment by Mika-** [comment]
All of those errors are coming from other extensions. Btw which firefox version are you on?

**Comment by hellfi** [comment]
I have this issue too, unfortunately
68.0+build3-0ubuntu0.19.04.1 amd64
debug seems to only say 
> TypeError: client.torrentOptions is undefined
> client.torrentOptions is undefined
when trying to save options, clicking the icons does nothing, clicking a magnet links brings me to
"https://torrent-control.invalid/magnet....." We can’t connect to the server at torrent-control.invalid.

**Comment by Mika-** [comment]
That seems to be the problem. Enhanced simple context menu doesn't check current client capabilities.
Fixed version should be available in a couple of minutes.

**Comment by psychopathio** [comment]
The issue has been resolved in my case, thanks for the effort & quick update.

**Comment by hellfi** [comment]
Update works fine, great work!

**Comment by jaypan** [comment]
Nice, thanks for the quick turn around on this plugin that's really indispensable  for me! Much appreciated.
