### ISSUE TITLE
[Feature Request] Label support for Deluge

### ISSUE THREAD

**Issue by Kopernikus1979** [Mika-/torrent-control#66]
Hi,

Would you be able to add label support for Deluge?
If you succeed I'll be more then happy to do a contribution.

Keep on the good work.

Thx

**Comment by Mika-** [comment]
Label support for Deluge was left out because Deluge would crash if you try to add a torrent with unkown label.

**Comment by Kopernikus1979** [comment]
Hi,

Would it be possible to add it anyway?
It’s a shortcoming of Deluge not TorrentControl, if you set in the “readme” that if you add an unknow label it will crash I see no problem.
Because this is a useful feature, for example I set a label that allows the torrents to seed to 1.5 and another one to 2.0 otherwise I have to login to the WebUI to set this manually.

Kind regards | Met vriendelijke groeten
Mit freundlichen Grüßen | Cordialement

DE SMET Nico

[cid:image001.jpg@01D550E5.6A7EB7C0]<https://www.kopernikus-networks.be/>

Van: Mika Simanainen <notifications@github.com>
Verzonden: zaterdag 10 augustus 2019 14:54
Aan: Mika-/torrent-control <torrent-control@noreply.github.com>
CC: Nico De Smet <nico.de.smet@kopernikus-networks.be>; Author <author@noreply.github.com>
Onderwerp: Re: [Mika-/torrent-control] [Feature Request] Label support for Deluge (#66)


Label support for Deluge was left out because Deluge would crash if you try to add a torrent with unkown label.

**Comment by Mika-** [comment]
Tested that current Deluge version actually stays running and logs label error with trace.

**Comment by Kopernikus1979** [comment]
That's good news, so you will implement it in a next release?

**Comment by Mika-** [comment]
Already implemented it, but didn't have time to test it properly.
As Deluge implements labels via addons they need an extra api request. That also means a need for supporting a scenario where adding a torrent may succeed but adding a label may fail.
Deluge also has at least two different addons for labels and documentation for both is non existent.
