### ISSUE TITLE
Jackett torrent links (http://127.0.0.1:9117)

### ISSUE THREAD

**Issue by 07416** [Mika-/torrent-control#67]
[Jackett](https://github.com/Jackett/Jackett) torrent download links start with `http://127.0.0.1:9117` and are downloaded locally instead of being handled by the addon. It's mandatory to add the torrents via context menu in order to upload to the remote client.

Is it possible to apply the same behavior to the Jackett's torrent files?

**Comment by Mika-** [comment]
I'll add this in a next version. Jackett has pretty recognizable url format.
