### ISSUE TITLE
Bug: qBittorrent, sequential + first/last pieces, Catch torrent URLs

### ISSUE THREAD

**Issue by weebsnore** [Mika-/torrent-control#68]
Client =

Torrent Control 0.2.11
Firefox 68.0.2

Server =

qBittorrent v4.1.7 Web UI
Ubuntu 18.04 LTS

These options are enabled in the extension options =

Sequential download
Prioritize first and last piece

Bug = 

Torrents start in the correct state (sequential + first/last) if added via the right click menu.

But not if added via "Catch torrent URLs".

Thanks for the extension - it's great!

Let me know if I can help track down the problem or if I'm missing something.

P.S. your menu bar item doesn't show up well against Firefox's dark theme :)

**Comment by Mika-** [comment]
Looks like torrent (and magnet) catching is missing this functionality. I'll fix it in to the next version.

Menu icon has light and dark versions, but Firefox's selection system broke somewhere around version 64 :(
