### ISSUE TITLE
Magnetic link = ok / Torrent files = fail

### ISSUE THREAD

**Issue by wellloaded** [Mika-/torrent-control#69]
As per title running torrent control on my firefox for WIndows 10.
The torrent machine is another windows10 device.

Long story short if I click on magnet links the download is passed over just as expected but if I click on .torrent file the torrent-control, very often but not always, gives me an error and nothing is passed over.

**Failed to add torrent. network Error.**

Am I missing anything in my config?

Thanks

**Comment by Mika-** [comment]
Some sites don't work with the addon. One example are private trackers that use JWT headers for authentication.
