### ISSUE TITLE
torrent fetch issue

### ISSUE THREAD

**Issue by smith149564** [Mika-/torrent-control#7]
I tried to add a torrent file to deluge with the right click context menu and it failed with the message "failed to read torrent".  After little debugging of the problem I found the type of the torrent is ""application/x-bittorrent; charset=utf-8" at line 64 of index.js, and thus string match fails triggering the error message.

Hopefully this info helps.

**Comment by Mika-** [comment]
Thanks, that helps a lot. I haven't seen content-type used with charset myself.
I'll add support for this in a next release.

**Comment by Mika-** [comment]
This should be working now in 0.1.5.

**Comment by smith149564** [comment]
Yes fixed in latest update. Thanx
