### ISSUE TITLE
Torrent Control no longer working on seedbox.io for me

### ISSUE THREAD

**Issue by OriginalCatalyst** [Mika-/torrent-control#71]
Thanks for any help everyone.
It stopped working last week of September. I'm not sure what day. I've attached some screen grabs that might help explain it. 

Torrent control
Clicking the magnet link gives a pop up with a snippet of html.
Clicking the torrent file to down load it, I get Unknown Response. (405 Not Allowed)

I've checked and Torrent Control and Firefox are updated. I'm sure I've made some simple change that broke it but I can not find it. I've removed/reinstalled Torrent Control, triple checked server link, username and password.
![Torrent file download intercept](https://user-images.githubusercontent.com/56038458/65977378-73e17380-e437-11e9-9192-c872f0aa142b.jpg)
![Torrent control magnet link](https://user-images.githubusercontent.com/56038458/65977379-73e17380-e437-11e9-9d46-c40cb68c5a43.jpg)
![torrent control settings](https://user-images.githubusercontent.com/56038458/65977381-73e17380-e437-11e9-81f8-03519144b37a.jpg)

**Comment by Mika-** [comment]
Looks like they have moved their ruTorrent installation under `/rutorrent/` and are using oldschool frames instead of doing a proper redirect. Does appending that to the server address fix this?

**Comment by OriginalCatalyst** [comment]
Yep that was it. They claimed nothing was changed on their end, but obviously something did. Thank you. and this is fixed!
