### ISSUE TITLE
make us set a default directory when using rutorrent

### ISSUE THREAD

**Issue by henriklb** [Mika-/torrent-control#77]
make us set a default directory when using rutorrent so I can add all my torrents with one click and have it directed to a set path. Thanks for making this btw much appreciated either way!

**Comment by Mika-** [comment]
Is there a use case where torrent clients own default directory settings isn't usable?

**Comment by henriklb** [comment]
No it is always usable. Setting a different dl dir is  a way to separate
files from each other. I.e. an automatic snatcher puts files in dir1 while
a manual extension use dir2.

**Comment by adamwinn** [comment]
I would like to see this too.  I have the exact same use case.
