### ISSUE TITLE
deluge add torrent issue

### ISSUE THREAD

**Issue by Etheral** [Mika-/torrent-control#78]
trying to add a torrent from rarbg (magnet link or .torrent link) to a deluge client on a media server on my local network.
using windows 10 I have setup a host path (media.home) to point to the server so if the IP changes I can change one place instead of multiple shortcuts/links etc.
setting the addon to use this path works to open deluge by clicking the icon but fails when I try to add a torrrent with a network error.
directly addressing the IP reports the server isnt' valid.
adding http:// to the front of either makes this wok (which is not easy given that firefox interprets the / to start the find box) 
could this be pre-filled,assumed, or maybe have a note that you need http for this to work?

**Comment by Mika-** [comment]
Server address actually is prefilled and client context aware. Eg. for Deluge the default value and placeholder is `http://127.0.0.1:8112/`, using right protocol, ip, port, and path if you are running client locally with default settings.
