### ISSUE TITLE
[Bug] Server configuration : "http://" prefix prevents TC to work

### ISSUE THREAD

**Issue by grantlee77** [Mika-/torrent-control#79]
Hello there,

I'm trying to use Torent Control with Seedbox.io services with no luck so far.
I believe the problem comes from the "server adress field" which requires "http://" prefix or else gives an error : 
![Screenshot_1](https://user-images.githubusercontent.com/10706675/71541254-619fa480-2956-11ea-8a02-f4d3f6bac5f7.jpg)

whereas official Seedbox tutorial specificaly asks not to put it :
![Firefox_Screenshot_2019-12-28T08-48-52 300Z](https://user-images.githubusercontent.com/10706675/71541321-687ae700-2957-11ea-9c26-84ddec15eb22.png)

Best regards

**Comment by Mika-** [comment]
Note that their documentation refers to _http**s**_ not _http_, so the protocol is right.

Seedbox.io is most likely still using frames (check #71 for more information), so the actual web interface address is something like `http://yourservice.seedbox.io/rutorrent/`

**Comment by grantlee77** [comment]
Thank you for your help.
You were right, everything now works as it should.

Best regards,
