### ISSUE TITLE
Finvip torrents aren't caught

### ISSUE THREAD

**Issue by 07416** [Mika-/torrent-control#80]
[Finvip](https://finvip.org/index.php) torrent links download locally. This behavior persists when Javascript is disabled.

Unfortunately the open sign-up has just ended and I don't have an invite. If the maintainer doesn't have an account I'll paste the page source code here (trying to remove all private information).

**Comment by Mika-** [comment]
Site looks like to be using Xbtit as it's base. According to it's [source code](https://github.com/btiteam/xbtit/blob/2cc39903ce53be292f3bcf28a2b28447d5017cca/style/xbtit_default/torrent.details.tpl#L32) download url schema is `/download.php?id=*infohash*&f=*filename*.torrent`, which should be catched.

Is there some kind of modified or older version that uses other schema (eg. `/download.php?id=*infohash*`)?

**Comment by 07416** [comment]
@Mika- Does this help?

`<a href='download.php?id=*infohash*&amp;f=*filename*.torrent&amp;key=*private key*'>`
