### ISSUE TITLE
Feature request: support for adding RSS feeds

### ISSUE THREAD

**Issue by 07416** [Mika-/torrent-control#86]
(by all means, close the issue if RSS feeds are outside the scope of this project)

[relevant documentation for ruTorrent ](https://github.com/Novik/ruTorrent/wiki/PluginRSS)

**Comment by Mika-** [comment]
Is there a specific way how you want to use this? "Add RSS-feed" option in context menu for links and selected text would be a self-explanatory way.

**Comment by 07416** [comment]
> 
> 
> Is there a specific way how you want to use this? "Add RSS-feed" option in context menu for links and selected text would be a self-explanatory way.

This sounds like an optimal method. Thank you in advance for implementing this feature request.
