### ISSUE TITLE
Adding torrent return a 502 proxy error everytime

### ISSUE THREAD

**Issue by Bananosucre** [Mika-/torrent-control#88]
Hi,

Everytime i try to add a torrent using Torrent Control, it does nothing and a few moment later a notification shows up and say 502 proxy error :

https://puu.sh/FrJUu/ff3728ef0a.png

Here is the configuration I have made : 

https://puu.sh/FrLvb/0812e2bcdf.png

Can you help me ?

Thanks

**Comment by Bananosucre** [comment]
UPDATE : It works perflectly with ruTorrent with this adress : https://xxxx.useed.fr/ (without the 443 port).

Why it doesnt work with Flood ?

**Comment by Mika-** [comment]
The default port for https is 443 so you don't need to specify it.

You can try to use browser devtools to check what are the differences between ui and addon requests. Many seedbox providers are using modified application versions which are not always compatible with official versions.
