### ISSUE TITLE
[FR] Please support redirected torrent links

### ISSUE THREAD

**Issue by zilexa** [Mika-/torrent-control#89]
Currently, when a user clicks on redirected torrent links, torrent-control catches it and sends it to Transmission, which fails because there is no torrent.
The .torrent link you're clicking returns a 3xx redirect to the tracker's torrent link which will then download correctly if followed. Please support this in torrent-control.

Reason: Jackett is a torrent-proxy for 100+ torrent indexer sites and APIs. Jackett can be used as source for Sonarr and Radarr. However it also handles manual user searches, which makes it incredibly easy and user friendly to search for a file across lots of sites using their API instead of the website. 
Jackett returns magnet links and redirected torrent links just to prevent the site APIs from overloading.

**Comment by Mika-** [comment]
Redirects are already being followed.

I haven't been able to reproduce this. Tested on Jacket 0.16.227.0 and download urls (`/dl/*site*/?jackett_apikey=...`) always return torrent file directly and are catched by addons whitelist.

Your specific site may have an anti ddos system that requires user meditation. Those are common to trigger eg. when actual torrents are served from a seperate domain than the actual site.
