### ISSUE TITLE
When Firefox is restarted I have to choose the addon as the magnet handler again

### ISSUE THREAD

**Issue by olliholliday** [Mika-/torrent-control#9]
Each time I restart Firefox I'm asked what to do with magnets on the first click. I choose "remember this decision" and it doesn't.

The URL that appears in the list of available handlers also appears as something strange that I can't remember right now - "http://invalid.handler/torrent" or something along those lines.

**Comment by S2-** [comment]
The magnet handler should be remembered across restarts. If ff does not remember your decision I think something is wrong in your profile, or it is a ff bug.

The handler url is defined [here](https://github.com/Mika-/torrent-control/blob/master/src/manifest.json#L48), and seems to be correct.

**Comment by Mika-** [comment]
I also first thought that it would be some sort of profile not persisting bug, but that would have many more visible side effects.

I can't find any documentation about protocol handler being reset on addon updates. But that would explain this behaviour as there's been 9 releases in a just 3 weeks. Release cycle will most likely get much slower from there on as most of the features are complete.
Mozillas release style with manual approvals doesn't fit properly to modern continous delivery style.

**Comment by olliholliday** [comment]
I hadn't realised it was updating silently - I guess that correlates with the preference being reset. It does seem a strange decision from moz.
