### ISSUE TITLE
[Bug] Clicking magnet links doesn't add torrent with firefox on linux

### ISSUE THREAD

**Issue by knivey** [Mika-/torrent-control#90]
The server I'm using is ruTorrent. The same config I have works fine on my windows machine.
On linux i can still add torrents by using the context menu. I do have catch torrent URLs checked.
When I click a magnet link nothing at all happens, its like i didn't click anything.

**Comment by Mika-** [comment]
Missing magnet uri handling is often caused by wrong application selection in `*Menu* > Options > General > Applications`. Protocol handling api is cross platform so there shouldn't be any differences.

**Comment by knivey** [comment]
Thanks, I simply had to go there and select Use Torrent Control Magnet Handler. Everything works fine now.
